### ISSUE TITLE
Use Case for NESA Data

### ISSUE THREAD

**Issue by mobile-appz** [anisotropi4/nesa#1]
Hi, thank you very much for providing this resource. I'm just wondering if you could please provide an example use case for the NESA data in terms of how it could be useful for an app aimed at rail passengers or staff. Specifically wondering if it is possible to derive signal or berth geographical postions from this data, or the distance along they are along the track. Many thanks.

**Comment by anisotropi4** [comment]
The honest answer is, I don't know. Although a fair question, the data is a bit niche and on its own probably not sufficient to do what you want.

The National Electronic Sectional Appendix are documents compiled by Network Rail makes up is the **official definition of railway infrastructure** in Great Britain and consist of Route Models and Maps, Route Availability, General Instructions and Specific Instructions based on a logical rather than geographic model. 

Of these, this is a text extract from these PDF files and currently excludes Route Models and Maps. These consist of embedded TIFF images and, in truth, I haven't got an OCR extract working to sufficient level of accuracy.

Given this, I see use cases for rail staff such as a driver, or in train service planning, train control and operations, or incident management. For example, if you want to work out whether an electric freight train of containers safely operate between North Pole depot via Mile End to Tilbury Docks, or where there are areas of track with poor adhesion. Less so for passengers.

Does that help?

**Comment by mobile-appz** [comment]
> The honest answer is, I don't know. Although a fair question, the data is a bit niche and on its own probably not sufficient to do what you want.
> 
> 
> 
> The National Electronic Sectional Appendix are documents compiled by Network Rail makes up is the **official definition of railway infrastructure** in Great Britain and consist of Route Models and Maps, Route Availability, General Instructions and Specific Instructions based on a logical rather than geographic model. 
> 
> 
> 
> Of these, this is a text extract from these PDF files and currently excludes Route Models and Maps. These consist of embedded TIFF images and, in truth, I haven't got an OCR extract working to sufficient level of accuracy.
> 
> 
> 
> Given this, I see use cases for rail staff such as a driver, or in train service planning, train control and operations, or incident management. For example, if you want to work out whether an electric freight train of containers safely operate between North Pole depot via Mile End to Tilbury Docks, or where there are areas of track with poor adhesion. Less so for passengers.
> 
> 
> 
> Does that help?

Thank you very much, that's useful to know.

**Comment by anisotropi4** [comment]
I realised that this was still open for uhh two years. So I'm going to close it. If you have any more questions, please shout.
